name: Releases

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  release-windows-x64:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
      - run: bash bin/release-windows.sh x64
      - uses: actions/upload-artifact@v4
        with:
          name: windows-x64
          path: dist/sonovel-windows_x64.tar.gz

  release-windows-arm64:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
      - run: bash bin/release-windows.sh arm64
      - uses: actions/upload-artifact@v4
        with:
          name: windows-arm64
          path: dist/sonovel-windows_arm64.tar.gz

  release-linux:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: [release-windows-x64, release-windows-arm64]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
      - run: |
          bash bin/release-linux.sh x64
          bash bin/release-linux.sh arm64
      - uses: actions/download-artifact@v4
        with:
          name: windows-x64
          path: dist
      - uses: actions/download-artifact@v4
        with:
          name: windows-arm64
          path: dist
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/*"
          token: ${{ secrets.GITHUB_TOKEN }} 