name: Releases

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  release-linux:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Build
        run: |
          bash bin/release-linux.sh x64
          bash bin/release-linux.sh arm64

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/*"
          token: ${{ secrets.GITHUB_TOKEN }} 